export const config = {
  //Finoux WebUAT 
       baseURL                 : 'http://219.91.228.145/SBIL_APPService_V3/SBILApi/',   
       imgURL                  : 'http://219.91.228.145/SBIL_APPService_V3/',
       imgURLNew               : 'http://219.91.228.145/SBIL_APPService_V3/',
       domain                  : '219.91.228.145',
       isLive                  : 'No',
       isHttpNative            : 'No',
  
  // Finoux Develpment Developer
        // baseURL                    : 'http://219.91.228.145/SBILDev/SBILApi/',    
        // imgURL                     : 'http://219.91.228.145/SBILDev_Admin/SbiLAdminSite',
        // domain                     : '219.91.228.145',
        // isLive                     : 'Yes',
        // isHttpNative               : 'No',
  
       
  // // SBI CLOUD WebUAT 
      // imgURL                     : 'https://uatapi.paisagenie.com/PG_UATAPI_V3',
      // baseURL                    : 'https://uatapi.paisagenie.com/PG_UATAPI_V3/SBILApi/',
      // domain                     : 'uatapi.paisagenie.com',
      // isLive                     : 'Yes',
      // isHttpNative               : 'Yes',
      // UpshotApplicationID        : 'eb81c527-2d74-47e2-86ea-5ee8a36f1cef',
      // UpshotApplicationOwnerID   : 'ff117318-2bce-46c5-a14f-61c0b61ee01a',
      // UpshotApplicationLaunchURL : 'https://cdn.goupshot.com/UpshotWebSDK/v1.4/upshot.min.js',


  // 23-12-2022 :: SBI CLOUD WebUAT -LIVE UAT MIX
    // imgURL                     : 'https://liveapi.paisagenie.com/PG_API_V3',
    //   baseURL                    : 'https://liveapi.paisagenie.com/PG_API_V3/SBILApi/',
    //   domain                     : 'liveapi.paisagenie.com',
    //   isLive                     : 'Yes',
    //   isHttpNative               : 'Yes',
    //   UpshotApplicationID        : 'eb81c527-2d74-47e2-86ea-5ee8a36f1cef',
    //   UpshotApplicationOwnerID   : 'ff117318-2bce-46c5-a14f-61c0b61ee01a',
    //   UpshotApplicationLaunchURL : 'https://cdn.goupshot.com/UpshotWebSDK/v1.4/upshot.min.js',
  

  // // Live PaisaGenie
      // imgURL                     : 'https://liveapi.paisagenie.com/PG_API_V3',
      // imgURLNew                  : 'https://liveapi.paisagenie.com/PG_API_V3/Images_new/',
      // baseURL                    : 'https://liveapi.paisagenie.com/PG_API_V3/SBILApi/',
      // domain                     : 'liveapi.paisagenie.com',
      // isLive                     : 'Yes',
      // isHttpNative               : 'Yes',
      UpshotApplicationID        : '16bedf19-2b97-4a5b-b81e-72c05383fb9c',
      UpshotApplicationOwnerID   : 'ff117318-2bce-46c5-a14f-61c0b61ee01a',
      UpshotApplicationLaunchURL : 'https://cdn.goupshot.com/UpshotWebSDK/v1.4/upshot.min.js',
  
  //test 
  // imgURL                     : 'https://cugapi.paisagenie.com/PG_API_V2',
  // baseURL                    : 'https://cugapi.paisagenie.com/PG_API_V2/SBILApi/',
  // domain                     : 'cugapi.paisagenie.com',
  // isLive                     : 'No',
  // isHttpNative                : 'Yes',

  loginReg: 'User/LoginRegistration',
  updateProfile: 'User/UpdateUserProfile',
  sendOTP: 'User/Login',
  validateOTP: 'User/ValidateOTP',
  setAgeIncome: 'User/SetAgeIncomeStatus',
  captureDeviceDetails: 'User/CaptureUserDeviceDetails',
  Logout: 'User/Logout',
  GetUserProfileMaster: 'User/UserProfileMaster',
  DefaultData: 'BaseAPI/Default',
  DefaultCal: 'Calculators/Default/',
  GetNetworthValue: 'Calculators/GetNetworthValue',
  GetSukanyaSamriddhiValues: 'Calculators/GetSukanyaSamriddhiValues',
  GetNPSValues: 'Calculators/GetNPSValues',
  CalculateHomeGoal: 'Goals/CalculateHomeGoal',
  CalculateCarGoal: 'Goals/CalculateCarGoal',
  GetFDValue: 'Calculators/GetFDValue',
  CalculateEducationGoal: 'Goals/CalculateEducationGoal',
  GetEMIValue: 'Calculators/GetEMIValue',
  CalculateWeddingGoal: 'Goals/CalculateWeddingGoal',
  GetLoanEligibilityValue: 'Calculators/GetLoanEligibilityValue',
  GetSIPValues: 'Calculators/GetSIPValues',
  GetCompoundingValues: 'Calculators/GetCompoundingValues',
  GetCoursewiseCountryList: 'Goals/GetCoursewiseCountryList',
  GetCourseMaster: 'Goals/GetCourseMaster',
  GetCourseDetails: 'Goals/GetCourseDetails',
  CalculateRetirementGoal: 'Goals/CalculateRetirementGoal',
  GetUserDetails: 'User/GetUserDetails',
  GetMasters: 'BaseAPI/GetMasters',
  GetPPFMaturityAmount: 'Calculators/GetPPFMaturityAmount',
  ArticleList: 'DiscoverPlan/ArticleList',
  SaveArticle: 'DiscoverPlan/SaveArticle',
  NewsUpdates: 'DiscoverPlan/NewsUpdates',
  ArticleCountByTags: 'DiscoverPlan/ArticleCountByTags',
  CardsLifePlanListing: 'DiscoverPlan/CardsLifePlanListing',
  Tips: 'DiscoverPlan/Tips',
  FAQs: 'DiscoverPlan/FAQs',
  RiskAssessmentQues: 'RiskAssessment/RiskAssessmentQues',
  InsertRiskAssessmentQA: 'RiskAssessment/InsertRiskAssessmentQA',
  UpdateUserAssets: 'User/UpdateUserAssets',
  GetUserAssetLiabilities: 'User/GetUserAssetLiabilities',
  CollectionMaster: 'DiscoverPlan/CollectionMaster',
  ArticleListingByTags: 'DiscoverPlan/ArticleListingByTags',
  ArticleDetails: 'DiscoverPlan/ArticleDetails',
  PopularGoals: 'DiscoverPlan/PopularGoals',
  UserPriorityQuestionList: 'DiscoverPlan/UserPriorityQuestionList',
  UpdateUserPriorityQuestion: 'DiscoverPlan/UpdateUserPriorityQuestion',
  CalculateTargetGoal: 'Goals/CalculateTargetGoal',
  UserNotificationCountNList: 'User/UserNotificationCountNList',
  SavedArticleList: 'DiscoverPlan/SavedArticleList',
  InsertUserGoal: 'Goals/InsertUserGoal',
  UpdateUserImage: 'User/UpdateUserImage',
  UpdateUserLiabilities: 'User/UpdateUserLiabilities',
  UpdateUserMonthlyExpense: 'User/UpdateUserMonthlyExpense',
  UpdateUserDependents: 'User/UpdateUserDependents',
  UpdateUserDetails: 'User/UpdateUserDetails',
  SavedGoalList: 'DiscoverPlan/SavedGoalList',
  DeleteUserGoal: 'Goals/DeleteUserGoal',
  UserRecentArticlesList: 'DiscoverPlan/UserRecentArticlesList',
  SearchArticle: 'DiscoverPlan/SearchArticle',
  GetUserTempGoalListing: 'Goals/GetUserTempGoalListing',
  InsertUserTempGoals: 'Goals/InsertUserTempGoals',
  DeleteUserTempGoals: 'Goals/DeleteUserTempGoals',
  GetUserSavedTempGoalListing: 'Goals/GetUserSavedTempGoalListing',
  UpdateUserSettingsFlag: 'User/UpdateUserSettingsFlag',
  UpdateUserLocation: 'User/UpdateUserLocation',
  CalculateFamilyProtectionGoal: 'Goals/CalculateFamilyProtectionGoal',
  CalculateHealthInsuranceGoal: 'Goals/CalculateHealthInsuranceGoal',
  UpdatePageUseCount: 'Reports/UpdatePageUseCount',
  UpdateFAQReadCount: '/Reports/UpdateFAQReadCount',
  UpdateNotificationReadCount: 'User/UpdateNotificationReadCount',
  UpdateUserNotificationId: 'User/UpdateUserNotificationId',
  AntiforgeryToken: 'AntiforgeryToken/Get',
  VerifyMPIN : 'User/VerifyMPIN',
  Infographics: 'DiscoverPlan/Infographics',
  CalculateFamilyProtectionGoalNew : "Goals/CalculateFamilyProtectionGoalNew",
  ImportUserSMS : 'User/ImportUserSMS',
  GetSMSDumpDate : 'User/GetSMSDumpDate',
  ExpenditureReview : 'User/ExpenditureReview',
  ExpenceReport : 'User/ExpenceReport',
  GetRecentSpends : 'User/GetRecentSpends',
  AddCategoryBudget : 'User/AddCategoryBudget',
  GetIncomeExpenses : 'User/GetIncomeExpenses',
  AddIncomeSource :'User/AddIncomeSource',
  AddUserExpenses : 'User/AddUserExpenses',
  GetUnCategoriesExpense : 'User/GetUnCategoriesExpense',
  GetMonthYearList : 'User/GetMonthYearList',
  GetExpenseTrade :'User/GetExpenseTrade',
  AddUnCategoriesTransaction: 'User/AddUnCategoriesTransaction',
  GetExpenseTradeReport: 'User/GetExpenseTradeReport',
  GetExpenseTypeWiseReport: 'User/GetExpenseTypeWiseReport',
  GetCategoriesExpense: 'user/GetCategoriesExpense',
  DeleteExpense: 'User/DeleteExpense',
  UpdateCustomerExpense: 'User/UpdateCustomerExpense',
  PeerBenchmark: 'User/PeerBenchmark',
  GetCustomerBudgetExpense: 'User/GetCustomerBudgetExpense',
  LikeDislikeArticle: 'DiscoverPlan/LikeDislikeArticle',
  SaveUserComment: 'DiscoverPlan/SaveUserComment',
  ArticleComments: 'DiscoverPlan/ArticleComments',
  SurveyQuizQuestion: 'DiscoverPlan/SurveyQuizQuestion',
  SubmitSurveyQuizAnswer: 'DiscoverPlan/SubmitSurveyQuizAnswer',
  SurveyQuizHeader: 'DiscoverPlan/SurveyQuizHeader',
  SurveyQuizRefArticle: 'DiscoverPlan/SurveyQuizRefArticle',
  GetHLVValues: 'Calculators/GetHLVValues',

}